"$schema" = "schemas/schema.json"

[[permission]]
identifier = "all"
description = "This enables all commands."
commands.allow = [
    "get_android_api_level",
    "get_name",
    "get_byte_length",
    "get_type",
    "get_mime_type",
    "get_metadata",
    "get_thumbnail",
    "get_thumbnail_as_bytes",
    "get_thumbnail_as_base64",
    "get_thumbnail_as_data_url",
    "get_fs_path",
    "list_volumes",
    "create_new_public_file",
    "create_new_public_image_file",
    "create_new_public_video_file",
    "create_new_public_audio_file",
    "scan_public_file",
    "set_public_file_pending",
    "request_public_files_permission",
    "check_public_files_permission",
    "create_new_file",
    "create_new_dir",
    "create_dir",
    "truncate_file",
    "copy_file",
    "count_all_file_streams",
    "close_all_file_streams",
    "open_read_file_stream",
    "open_read_text_file_lines_stream",
    "open_write_file_stream",
    "read_file",
    "read_file_as_base64",
    "read_file_as_data_url",
    "read_text_file",
    "write_file",
    "write_text_file",
    "read_dir",
    "rename_file",
    "rename_dir",
    "remove_file",
    "remove_empty_dir",
    "remove_dir_all",
    "check_picker_uri_permission",
    "persist_picker_uri_permission",
    "check_persisted_picker_uri_permission",
    "release_persisted_picker_uri_permission",
    "release_all_persisted_picker_uri_permissions",
    "show_open_file_picker",
    "show_open_dir_picker",
    "show_save_file_picker",
    "show_share_file_dialog",
    "show_view_file_dialog",
    "show_view_dir_dialog",
    "listSecurityScopedBookmarks",
    "resolveSecurityScopedBookmark",
    "releaseSecurityScopedBookmark",
    "persistSecurityScopedBookmark",
    "readFile",
    "readTextFile",
    "writeFile",
    "writeTextFile",
    "readDir",
    "createDir",
    "createNewFile",
    "createNewDir",
    "copyFile",
    "renameFile",
    "renameDir",
    "removeFile",
    "removeEmptyDir",
    "removeDirAll",
    "exists",
    "getMetadata",
    "showOpenFilePicker",
    "showOpenDirPicker",
    "showSaveFilePicker"
]
